import chalk from 'chalk';
import { scanRepository } from '../services/scanner';
import { calculateScore, ScoreResult } from '../services/scorer';
import { MATURITY_LEVELS } from '../models/levels';
import { scanCommand, ScanFormat } from './scan';

export type ReportFormat = 'json' | 'markdown' | 'terminal' | 'csv';

export async function reportCommand(
  targetPath: string,
  format: ReportFormat
): Promise<void> {
  try {
    const scanResult = await scanRepository(targetPath);
    const score = calculateScore(scanResult);

    switch (format) {
      case 'json':
        printJsonReport(score, scanResult);
        break;
      case 'markdown':
        printMarkdownReport(score, scanResult);
        break;
      case 'csv':
        printCsvReport(score, scanResult);
        break;
      case 'terminal':
      default:
        await scanCommand(targetPath, format as ScanFormat);
        break;
    }
  } catch (error) {
    console.error(chalk.red(`Error: ${(error as Error).message}`));
    process.exit(1);
  }
}

function printJsonReport(score: ScoreResult, scanResult: Awaited<ReturnType<typeof scanRepository>>): void {
  const report = {
    repository: scanResult.basePath,
    timestamp: new Date().toISOString(),
    maturity: {
      level: score.maturityLevel,
      name: score.maturityName,
      description: score.maturityDescription
    },
    quality: {
      score: score.qualityScore,
      maxScore: 10,
      weight: score.totalWeight,
      commitBonus: score.commitBonus
    },
    metrics: score.qualityMetrics,
    tools: score.toolBreakdown,
    references: scanResult.referenceValidation,
    commits: scanResult.commitCounts,
    recommendations: score.recommendations,
    levels: MATURITY_LEVELS.map(l => ({
      level: l.level,
      name: l.name,
      achieved: l.level <= score.maturityLevel
    }))
  };

  console.log(JSON.stringify(report, null, 2));
}

function printMarkdownReport(score: ScoreResult, scanResult: Awaited<ReturnType<typeof scanRepository>>): void {
  const lines: string[] = [];

  lines.push('# Context Frame Report\n');
  lines.push(`**Repository:** \`${scanResult.basePath}\`\n`);
  lines.push(`**Generated:** ${new Date().toISOString()}\n`);

  // Maturity Level
  lines.push('## Maturity Level\n');
  lines.push(`| Level | Status |`);
  lines.push(`|-------|--------|`);
  for (const level of MATURITY_LEVELS) {
    const status = level.level <= score.maturityLevel ? '✅' : '⬜';
    const current = level.level === score.maturityLevel ? ' ← Current' : '';
    lines.push(`| ${level.level}. ${level.name} | ${status}${current} |`);
  }
  lines.push('');

  lines.push(`**Current Level:** ${score.maturityLevel} - ${score.maturityName}\n`);
  lines.push(`> ${score.maturityDescription}\n`);

  // Quality Score
  lines.push('## Quality Score\n');
  lines.push(`**Score:** ${score.qualityScore}/10\n`);
  lines.push(`**Total Weight:** ${score.totalWeight}\n`);
  lines.push(`**Commit Bonus:** ${score.commitBonus}\n`);

  // Progress bar in markdown
  const filled = Math.round(score.qualityScore);
  const bar = '█'.repeat(filled) + '░'.repeat(10 - filled);
  lines.push(`\`${bar}\`\n`);

  // Metrics
  lines.push('## Quality Metrics\n');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Sections | ${score.qualityMetrics.sections} |`);
  lines.push(`| File Paths | ${score.qualityMetrics.filePaths} |`);
  lines.push(`| Commands | ${score.qualityMetrics.commands} |`);
  lines.push(`| Constraints | ${score.qualityMetrics.constraints} |`);
  lines.push(`| Word Count | ${score.qualityMetrics.wordCount} |`);
  lines.push('');

  // Tool Coverage
  lines.push('## Tool Coverage\n');
  if (Object.keys(score.toolBreakdown).length === 0) {
    lines.push('*No AI context files detected*\n');
  } else {
    for (const [tool, data] of Object.entries(score.toolBreakdown)) {
      lines.push(`### ${tool}\n`);
      lines.push(`**Weight:** ${data.weight}\n`);
      lines.push('**Files:**');
      for (const file of data.files) {
        lines.push(`- \`${file}\``);
      }
      lines.push('');
    }
  }

  // Recommendations
  if (score.recommendations.length > 0) {
    lines.push('## Recommendations\n');
    for (const rec of score.recommendations) {
      lines.push(`- ${rec}`);
    }
    lines.push('');
  }

  lines.push('## Reference Validation\n');
  lines.push(`Resolved: ${scanResult.referenceValidation.resolvedReferences}/${scanResult.referenceValidation.totalReferences} (${Math.round(scanResult.referenceValidation.resolutionRate * 100)}%)\n`);
  if (scanResult.referenceValidation.brokenReferences.length > 0) {
    lines.push('Broken References:');
    for (const broken of scanResult.referenceValidation.brokenReferences.slice(0, 10)) {
      lines.push(`- ${broken.sourceFile} -> ${broken.reference}`);
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('*Generated by [Context Frame](https://github.com/context-frame)*');

  console.log(lines.join('\n'));
}

function printCsvReport(score: ScoreResult, scanResult: Awaited<ReturnType<typeof scanRepository>>): void {
  const headers = [
    'repository',
    'timestamp',
    'level',
    'level_name',
    'quality_score',
    'quality_weight',
    'commit_bonus',
    'sections',
    'file_paths',
    'commands',
    'constraints',
    'word_count',
    'tools_detected',
    'refs_total',
    'refs_resolved',
    'refs_rate',
    'context_files',
    'context_files_5plus'
  ];

  const commitCounts = scanResult.commitCounts;
  const filesWithFivePlus = Object.values(commitCounts).filter(count => count >= 5).length;
  const row = [
    scanResult.basePath,
    new Date().toISOString(),
    score.maturityLevel,
    score.maturityName,
    score.qualityScore,
    score.totalWeight,
    score.commitBonus,
    score.qualityMetrics.sections,
    score.qualityMetrics.filePaths,
    score.qualityMetrics.commands,
    score.qualityMetrics.constraints,
    score.qualityMetrics.wordCount,
    scanResult.toolsDetected.length,
    scanResult.referenceValidation.totalReferences,
    scanResult.referenceValidation.resolvedReferences,
    scanResult.referenceValidation.resolutionRate.toFixed(2),
    Object.keys(commitCounts).length,
    filesWithFivePlus
  ];

  console.log(headers.join(','));
  console.log(row.map(value => `"${String(value).replace(/"/g, '""')}"`).join(','));
}
